
export const CLIENTS_URL = '/clients'
export const CARS_URL = '/cars'
export const CAR_MODELS_URL = '/car-models'
export const MILEAGES_URL = '/mileages'
export const ORDERS_URL = '/orders'
export const SERVICES_URL = '/services'
export const PRODUCTS_URL = '/products'
export const EMPLOYEES_URL = '/employees'
export const COMMENTS_URL = '/comments'
export const ORDER_SERVICES_URL = '/order-services'

export const ORDER_PRODUCTS_URL = '/order-products'
export const ORDER_EMPLOYEES_URL = '/order-employees'
export const COMMANDS_URL = '/commands'
export const APPOINTMENTS_URL = '/appointments'