import type {Metadata} from "next";
import Navbar from "@/components/common/navbar/Navbar";
import {SidebarInset, SidebarProvider,} from "@/components/ui/sidebar"
import {AppSidebar} from "@/components/common/sidebar/AppSidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (


        <SidebarProvider>
            <AppSidebar/>
            <SidebarInset>
                <Navbar/>
                <main className={'flex flex-1 flex-col gap-4 p-4'}>
                    {children}
                </main>
            </SidebarInset>
        </SidebarProvider>

    );
}
