import type {Metadata} from "next";
import Navbar from "@/components/common/navbar/Navbar";
import {SidebarInset, SidebarProvider,} from "@/components/ui/sidebar"
import {AppSidebar} from "@/components/common/sidebar/AppSidebar";
import Hydration from "@/providers/Hydration";
import {Noto_Sans} from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const font = Noto_Sans({
    weight: [
        '300',
        '400',
        '600',
        '700'],
    subsets: ['latin', "cyrillic-ext"]
})


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <Hydration>
            <SidebarProvider>
                <AppSidebar/>
                <SidebarInset>
                    <Navbar/>
                    <main className={`flex flex-1 flex-col gap-4 p-4 bg-muted/40  ${font.className}`}>
                        {children}
                    </main>
                </SidebarInset>
            </SidebarProvider>
        </Hydration>

    );
}
